# Generated by Django 5.1.1 on 2025-03-23 01:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Reward',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #     ],
        # ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('downlines', models.ManyToManyField(related_name='matching_downlines', to='members.account')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.account', verbose_name='Grantee account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount')),
                ('payment_type', models.CharField(choices=[('matching_payment', "Paiement d'équilibres"), ('referral_payment', 'Paiement de parrainages'), ('purchase_payment', "Paiement de bonus d'achat")], max_length=50, null=True)),
                ('bonuses', models.JSONField(default=list)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Paid on')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.account', verbose_name='Grantee account')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.office')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.account', verbose_name='Grantee account')),
                ('sale_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_bonuses', to='stock.saledetail')),
            ],
            options={
                'verbose_name_plural': 'Purchase bonuses',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('downline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_downline', to='members.account')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.account', verbose_name='Grantee account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
