# Generated by Django 5.0.6 on 2024-08-11 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Referral amount')),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Refer date')),
                ('downlines', models.ManyToManyField(related_name='downlines', to='members.account', verbose_name='Downline accounts')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grandee', to='members.account', verbose_name='Grantee account')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Paid on')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.account', verbose_name='Grantee account')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Referral amount')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Refer date')),
                ('downline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.account', verbose_name='Downline account')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='members.account', verbose_name='Grantee account')),
            ],
        ),
    ]
