# Generated by Django 5.2.4 on 2025-07-18 00:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='_ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/gifts')),
                ('mark', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='_ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('downlines', models.ManyToManyField(related_name='matching_downlines', to='members.account')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.account', verbose_name='Grantee account')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.office')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount')),
                ('payment_type', models.CharField(choices=[('matching_payment', "Paiement d'équilibres"), ('referral_payment', 'Paiement de parrainages'), ('purchase_payment', "Paiement de bonus d'achat produit")], max_length=50, null=True)),
                ('bonuses', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Paid on')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.account', verbose_name='Grantee account')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.office')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='_ID')),
                ('equivalent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_number', models.IntegerField(blank=True, null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('matching', 'Equilibres'), ('referral', 'Parrainages')], max_length=50, null=True)),
                ('gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.gift')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.promotion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_to_be_paid', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.account', verbose_name='Grantee account')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.office')),
                ('sale_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_bonuses', to='stock.saledetail')),
            ],
            options={
                'verbose_name_plural': 'Purchase bonuses',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_downline', to='members.account')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.account', verbose_name='Grantee account')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.office')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='_ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equivalent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_number', models.IntegerField(blank=True, null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('matching', 'Equilibres'), ('referral', 'Parrainages')], max_length=50, null=True)),
                ('gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.gift')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
