# Generated by Django 5.1.1 on 2024-11-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('matching_payment', "Paiement d'équilibres"), ('referral_payment', 'Paiement de parrainages'), ('purchase_payment', "Paiement de bonus d'achat")], max_length=50, null=True),
        ),
    ]
