# Generated by Django 5.1.1 on 2024-11-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bonuses',
            field=models.JSONField(default=list),
        ),
    ]
