# Generated by Django 5.1.1 on 2025-03-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_purchasebonus_amount_to_be_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('matching_payment', "Paiement d'équilibres"), ('referral_payment', 'Paiement de parrainages'), ('purchase_payment', "Paiement de bonus d'achat produit")], max_length=50, null=True),
        ),
    ]
