# Generated by Django 5.1.1 on 2024-11-27 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_initial'),
        ('prices', '0003_payment_bonuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.office'),
        ),
    ]
