# Generated by Django 5.2.4 on 2025-08-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_alter_matching_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='is_validated',
            field=models.BooleanField(default=True),
        ),
    ]
