# Generated by Django 5.1.1 on 2025-04-01 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_account_referral_account'),
        ('prices', '0004_alter_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebonus',
            name='amount_to_be_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='referral',
            name='downline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_downline', to='members.account'),
        ),
    ]
