# Generated by Django 5.1.1 on 2025-04-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_alter_purchasebonus_amount_to_be_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='matching',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchasebonus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchasebonus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
