# Generated by Django 5.1.1 on 2025-06-01 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_alter_matching_created_at_alter_matching_updated_at_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebonus',
            name='sale_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_bonuses', to='stock.saledetail'),
        ),
    ]
