# Generated by Django 5.1.1 on 2025-06-11 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_account_referral_account'),
        ('prices', '0007_alter_purchasebonus_sale_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.office'),
        ),
        migrations.AddField(
            model_name='purchasebonus',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.office'),
        ),
        migrations.AddField(
            model_name='referral',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.office'),
        ),
    ]
