# Generated by Django 5.2.4 on 2025-07-18 00:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('begin', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('package_price_percent', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('reccords_number', models.IntegerField()),
                ('used_reccords_number', models.IntegerField(default=0, editable=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
