# Generated by Django 5.2.4 on 2025-08-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchingprice',
            options={'ordering': ['begin']},
        ),
        migrations.AlterUniqueTogether(
            name='matchingprice',
            unique_together={('begin', 'end')},
        ),
    ]
