# Generated by Django 5.2.4 on 2025-08-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_matchingprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingprice',
            name='daily_max_matching',
            field=models.IntegerField(default=0),
        ),
    ]
