# Generated by Django 5.1.1 on 2024-10-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_default_password',
            field=models.BooleanField(default=True),
        ),
    ]
