# Generated by Django 5.0.6 on 2024-08-11 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rewards',
            field=models.ManyToManyField(blank=True, to='prices.reward', verbose_name='Account rewards'),
        ),
        migrations.AddField(
            model_name='account',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='members.member', verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='account',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.package', verbose_name='Package'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='member_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.account', verbose_name='Member account'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='members.office', verbose_name='Office'),
        ),
    ]
