# Generated by Django 5.1.1 on 2024-09-17 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0002_initial'),
        ('members', '0001_initial'),
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rewards',
            field=models.ManyToManyField(blank=True, to='prices.reward', verbose_name='Account rewards'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.country', verbose_name='Location Country'),
        ),
        migrations.AddField(
            model_name='office',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offices', to='members.location'),
        ),
        migrations.AddField(
            model_name='account',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_offices_set', to='members.office', verbose_name='Account Office Recorder'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='member_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.account', verbose_name='Member account'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='members.office', verbose_name='Office Creator'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.package', verbose_name='Package'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.subscriptioncode'),
        ),
    ]
