# Generated by Django 5.1.1 on 2025-03-19 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='pvs',
        ),
    ]
