# Generated by Django 5.1.1 on 2025-04-01 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_account_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='referral_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.account', verbose_name='Referral account'),
        ),
    ]
