# Generated by Django 5.1.1 on 2025-07-12 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_account_referral_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_offices_set', to='members.office'),
        ),
    ]
