# Generated by Django 5.1.1 on 2025-07-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_account_office'),
        ('prices', '0009_gift_promotion_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='account_promotions', to='prices.promotion'),
        ),
        migrations.AddField(
            model_name='account',
            name='rewards',
            field=models.ManyToManyField(blank=True, related_name='account_rewards', to='prices.reward'),
        ),
    ]
